### PR TITLE
mail: add mail router and first interface

### PR DESCRIPTION
**Pull request by YohannFin**
Hi Pichot, this is preview of the first version of the mail app. If you want to share about this project you can contact me with discord : Flyander#6318.

mailApp

### CODE REVIEW

**Comment by PichotM** [comment]
Hi, thank you for your pull request
I'll try to review it as soon as possible

**Comment by PichotM** [comment]
And also if you can, put everything in english

**Comment by YohannFin** [comment]
Yes sure, i correct this soon.

**Comment by YohannFin** [comment]
It's better like that.
Mail_firstVersion

**Comment by PichotM** [comment]
This will be merged Saturday or Sunday

**Comment by YohannFin** [comment]
Ok i add the final design of inbox, i start write mail part when i have time. But care in your app, don't use `<div className="app-container">` but use `<React.Fragment>` it's fix the bug where click don't working

**Comment by YohannFin** [comment]
I have also add the real time in header

**Pull request merged**
